plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'maven-publish'
}

group = 'com.cheong'
version = '0.0.1-SNAPSHOT'
description = 'common-core-reactive'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}


repositories {
    mavenCentral()
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.1.1')
    annotationProcessor platform('org.springframework.boot:spring-boot-dependencies:4.1.1')
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
