spring:
  application:
    name: user-service
  r2dbc:
    username: ${DATASOURCE_USERNAME:db_admin}
    password: ${DATASOURCE_PASSWORD:secure_password_123}
    url: r2dbc:${DATASOURCE_URL:postgresql://localhost:5432/users}
  webflux:
    api-version:
      supported:
        - v1
      use:
        header: X-API-VERSION
      default: v1
  messages:
    basename: messages/messages
  liquibase:
    url: jdbc:${DATASOURCE_URL:postgresql://localhost:5432/users}
    user: ${DATASOURCE_USERNAME:db_admin}
    password: ${DATASOURCE_PASSWORD:secure_password_123}
logging:
  level:
    org.springframework.web.reactive.result.method.annotation.ControllerMethodResolver: TRACE
    org.springframework.web: TRACE
    com.cheong.common.core.reactive: TRACE